### ISSUE TITLE
where to find tumor purity info?

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [javadnoorb/HistCNN#2]
Hi Javad,
In the manuscript from bioRxv, it said that "The distributions of TPF values were generally higher than the pathologist-reported tumor purities available on TCGA."

I wonder where I can find the tumor purity information on the TCGA website. For bladder cancer, I didn't find such information. Is it not available for all cohorts?

Second question is about background removal to select normal or tumor tiles. 
When DeepPATH was used to remove background noise from normal cells for a tumor tile, is "-B " set as "-B 1"?
Also, in theory, to keep more tiles be used for training, would it be better to take full use of data if tiles are split as small as possible?
Thanks,
Zhenzhen

**Comment by javadnoorb** [comment]
Hi Zhenzhen,

You can find the purity information from the biospecimen files (you'll need to parse the xml files). I think cbioportal also has this information tabulated, but I've never used that so I may be mistaken.

I'm not sure what "-B " is, but to give you an idea, similar to DeepPATH we removed any tiles which had more than 50% background. Background was defined as any pixel with intensity > 220 (for 256 bit-depth image). 

You can reduce the size of the tiles, but you will end up capturing other information, for example instead of cell density you may capture cell shape. I don't know what the proper size is. We tested a few and settled on 512x512. But this was arbitrary. You can play around with it. In terms of increasing the number of tiles, that probably won't be the bottleneck in the analysis, as you get many tiles even with 512x512. The limiting factor in all of these analyses is the number of slides rather than the number of tiles. So you may want to check if you have enough samples for your specific analysis. We used minimum 25 samples if I recall correctly. But again there's no golden rule for this as far as I know. 

-J

**Comment by zhenzhenyang-psu** [comment]
Hi Javad,
Thanks for your reply! I really appreciate it!
Yes, I later also found that the biospecimen file has such information, thank you!
I previously thought background of a normal tile was considered as noise from tumor cells. From your reply that "Background was defined as any pixel with intensity >220", did you mean to remove noise from over-exposure or stuff like that?
In your paper, it said that "after removal of background regions, all tiles in a normal image are assumed normal and all tiles in a tumor image are assumed tumor". I also had such concern. As you know, slides labeled as "tumor" have different levels of tumor purity. So when a slide is split into several hundred tiles, each tile is non-homogenous. Some tiles may contain a high fraction of tumor cells, some have a very small number of tumor cells. So I wonder how to ensure this? 
Or you allowed some error in the training set? will selecting slides of high tumor fraction help?

Thank you for your thoughts on the number of tiles and slides as well.

Zhenzhen

**Comment by javadnoorb** [comment]
Hi Zhenzhen,
No, background is just the white regions. We didn't do any overexposure removal or similar preprocessing. 
Assuming all tiles of tumor as tumor, is not great. Although TCGA is generally high-purity and we may get away with this. This is an issue with the field in cases where only slide-level information is available. There are some workarounds for it, but in the manuscript we are arguing that despite existence of heterogeneity and some incorrect ground truth we're still able to get high classification results on the slide level.
-J

**Comment by zhenzhenyang-psu** [comment]
hi Javad,
That is great to know!
zhenzhen

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
